#!/bin/zsh                                                                                                                                                                                                                                  

#svnで管理しているディレクトリのパス
svnDirectoryPath="xxxxx"

#カレントディレクトリ以下でgitで管理しているファイルの一覧
files=( ${(@f)"$(git ls-files)"} )

for file in $files; do
 	if [ $file != ".gitignore"]; then
		#パスに含まれているディレクトリが存在しているか
		if [ -e ${svnDirectoryPath}`dirname ${file}` ]; then
		else
			mkdir -p  $svnDirectoryPath`dirname ${file}`
		fi 
  #コピー
  cp $file $svnDirectoryPath$file 
	fi
done
